version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgres_boilerplate_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /docker/postgress:/var/lib/postgresql/data
    networks:
      - postgres_boilerplate_api_network
      
  goserver:
    image: registry.gitlab.com/engtiago/go-boilerplate/go-server:latest
    container_name: goserver
    ports:
      - "3000:3000"
    networks:
      - postgres_boilerplate_api_network

networks:
  postgres_boilerplate_api_network:
    driver: bridge

volumes:
  postgres_boilerplate_api_data:
